name: Github Szumtions
author: Jan Szewczyk (Szum-Tech)
description: Custom GitHub actions created to make your repository great again
branding:
  color: blue
  icon: activity

runs:
  using: node16
  main: dist/index.js
