name: Labels
author: Jan Szewczyk (Szum-Tech)
description: Custom GitHub action created with TypeScript

inputs:
  GITHUB_TOKEN:
    default: ${{ github.token }}
    description: "GitHub access token."
    required: false

runs:
  using: node16
  main: ../dist/labels/index.js
