name: Labels
author: Jan Szewczyk (Szum-Tech)
description: Custom GitHub action created with TypeScript

inputs:
  GITHUB_TOKEN:
    default: ${{ github.token }}
    description: GitHub access token.
    required: false

  CUSTOM_CONFIG_PATH:
    description: Path to your custom labels configuration file. It should be YAML file.
    required: false

  DISABLE_DEFAULT_CONFIG:
    default: "FALSE"
    description: Flag that specifies whether the default labels configuration is used.
    required: false

runs:
  using: node16
  main: ../dist/labels/index.js
